Venjobs/config/routes.rb
Rails.application.routes.draw do
  devise_for :account_users, skip: [:sessions]
  as :account_user do
    get '/login', to: 'devise/sessions#new', as: :new_account_user_session
    get '/register', to: 'devise/registrations#new'
    post '/login', to: 'my_devise/sessions#create', as: :account_user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_account_user_session
    get '/register/1', to: 'my_devise/registrations#new', as: :new_account_user_registrantion
    post '/register/2/', to: 'my_devise/registrations#create', as: :create1_account_user_registrantion
    get '/register/2/', to: 'my_devise/registrations#show', as: :create_account_user_registrantion
    get '/register/3', to: 'my_devise/confirmations#show', as: :show_account_user_registrantation
    post 'register/3', to: 'my_devise/registrations#my_update', as: :update_account_user_registrantaion
    get '/forgot_password', to: 'devise/passwords#new', as: :new_user_password
    post '/forgot_password', to: 'my_devise/passwords#create', as: :password
    get '/reset_password/', to: 'my_devise/passwords#my_edit', as: :edit_password
    put '/forgot_password/', to: 'my_devise/passwords#update'
    get 'admin/login', to: 'my_devise/sessions#admin_login', as: :admin_login
    post 'admin/login', to: 'my_devise/sessions#do_admin_login', as: :new_admin_session
  end
  get '/jobs/', to: 'jobs#search', as: :search_job
  get '/jobs/favorite', to: 'jobs#favorite'
  post '/favorites/:id', to: 'favorites#create', as: :create_favorite
  get '/jobs/search/', to: 'jobs#search'
  post '/jobs/search/', to: 'jobs#search', as: :search_jobs
  get '/jobs/city/:city', to: 'jobs#search'
  get '/detail/:job_id', to: 'jobs#show'
  get '/jobs/industry/:industry', to: 'jobs#search'
  get '/my/', to: 'users#my', as: :user_my
  get '/apply/', to: 'applies#new'
  post '/confirm', to: 'applies#confirm1', as: :confirm1_apply
  get '/confirm', to: 'applies#confirm2', as: :confirm2_apply
  post '/done', to: 'applies#create', as: :create_apply
  get '/done', to: 'applies#done', as: :done_apply
  get 'my/info', to: 'users#info'
  post 'my/info', to: 'users#update', as: :update_user
  root to: 'jobs#index'
  get '/industrys', to: 'categories#show'
  get 'cities', to: 'cities#show'
  get '/my/favorites', to: 'favorites#index'
  delete '/my/favorites/:id', to: 'favorites#remove'
  get '/history', to: 'histories#index'
  delete '/history/:id', to: 'histories#remove', as: :remove_history
  get 'my/jobs', to: 'jobs#applied'
  get 'admin/applies', to: 'jobs#admin_job', as: :applies_admin
  get 'admin/download', to: 'jobs#admin_job', as: :export_applies
  post 'admin/applies', to: 'jobs#admin_job', as: :admin_job
  get '/suggestions/:keyword', to: 'jobs#spellcheck_solr'
end

Venjobs/app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venjobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <div class="header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">
              <%= image_tag 'https://zigexn.vn/assets/media/logo-e5bdc0020427455913196830ae4370fb3a6437f3be67875289bde098bc2c545f.png' %> 
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content: end;">
              <div class="navbar-nav">
                <% if account_user_signed_in? %>
                  <a class="nav-link active" aria-current="page" href="/my/favorites"><i class="fa-solid fa-star"></i> <span id="favorite_count"><%= current_account_user.favorites.count %></span></a>
                  <a class="nav-link" href="/history"><i class="fa-solid fa-clock-rotate-left"></i> History</a>
                  <%= link_to '/my', class: 'nav-link' do %>
                    <i class="fa-solid fa-user"></i> My Page
                  <% end %> 
                  <%= link_to destroy_account_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> Logout
                  <% end %> 
                <% else %> 
                  <a class="nav-link active" aria-current="page" href="/my/favorites"><i class="fa-solid fa-star"></i> Favorite</a>
                  <a class="nav-link" href="/history"><i class="fa-solid fa-clock-rotate-left"></i> History</a>
                  <a class="nav-link" href="/login"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
                  <a class="nav-link" href="/register/1"><i class="fa-solid fa-registered" aria-hidden="true"></i> Register</a>
                <% end %> 
              </div>
            </div>
          </div>
        </nav>    
      </div>
      <div id="main-content">
        <%= yield %>
      </div>
      <div id="push"></div>
    </div>
    <div id="footer" class="navbar-dark bg-dark">
      <footer>
        <div class="contact-detail row">
          <div class="col">
            <h4 class="white">ADDRESS</h4>
            <p> Floor 11, VINA BUILDING,<br>
            131 Xo Viet Nghe Tinh, Ward 17,<br>
            Binh Thanh District, Ho Chi Minh City, VietNam</p>
          </div>
          <div class="col">
            <h4 class="white">EMAIL US</h4>
            <p>info@zigexn.vn</p>
          </div>
          <div class="col">
            <h4 class="white">CALL US</h4>
            <p> (84)-838-633-399</p>
          </div>
          <p class="text-right"><%= "ZIGExN VeNtura 2022"%></p>
        </div>
    </div>
      </footer>
      </div>
      <script src="/assets/jobs/search.js"></script>
  </body>
</html>

Venjobs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venjobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <div class="header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">
              <%= image_tag 'https://zigexn.vn/assets/media/logo-e5bdc0020427455913196830ae4370fb3a6437f3be67875289bde098bc2c545f.png' %> 
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="justify-content: end;">
              <div class="navbar-nav">
                <% if account_user_signed_in? %>
                  <% if current_account_user.user? %> 
                    <a class="nav-link active" aria-current="page" href="/my/favorites"><i class="fa-solid fa-star"></i> <span id="favorite_count"><%= current_account_user.favorites.count %></span></a>
                    <a class="nav-link" href="/history"><i class="fa-solid fa-clock-rotate-left"></i> History</a>
                    <%= link_to '/my', class: 'nav-link' do %>
                      <i class="fa-solid fa-user"></i> My Page
                    <% end %> 
                    <%= link_to destroy_account_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' do %>
                      <i class="fa-solid fa-right-from-bracket"></i> Logout
                    <% end %> 
                  <% elsif current_account_user.admin? %> 
                    <%= link_to destroy_account_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' do %>
                      <i class="fa-solid fa-right-from-bracket"></i> Logout
                    <% end %> 
                  <% end %> 
                <% else %> 
                  <a class="nav-link active" aria-current="page" href="/my/favorites"><i class="fa-solid fa-star"></i> Favorite</a>
                  <a class="nav-link" href="/history"><i class="fa-solid fa-clock-rotate-left"></i> History</a>
                  <a class="nav-link" href="/login"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
                  <a class="nav-link" href="/register/1"><i class="fa-solid fa-registered" aria-hidden="true"></i> Register</a>
                <% end %> 
              </div>
            </div>
          </div>
        </nav>    
      </div>
      <div id="main-content">
        <%= yield %>
      </div>
      <div id="push"></div>
    </div>
    <div id="footer" class="navbar-dark bg-dark">
      <footer>
        <div class="contact-detail row">
          <div class="col">
            <h4 class="white">ADDRESS</h4>
            <p> Floor 11, VINA BUILDING,<br>
            131 Xo Viet Nghe Tinh, Ward 17,<br>
            Binh Thanh District, Ho Chi Minh City, VietNam</p>
          </div>
          <div class="col">
            <h4 class="white">EMAIL US</h4>
            <p>info@zigexn.vn</p>
          </div>
          <div class="col">
            <h4 class="white">CALL US</h4>
            <p> (84)-838-633-399</p>
          </div>
          <p class="text-right"><%= "ZIGExN VeNtura 2022"%></p>
        </div>
    </div>
      </footer>
      </div>
      <script src="/assets/jobs/search.js"></script>
  </body>
</html>