Venjobs/config/routes.rb
Rails.application.routes.draw do
  devise_for :account_users, skip: [:sessions]
  as :account_user do
    get '/login', to: 'devise/sessions#new', as: :new_account_user_session
    get '/register', to: 'devise/registrations#new'
    post '/login', to: 'my_devise/sessions#create', as: :account_user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_account_user_session
    get '/register/1', to: 'my_devise/registrations#new', as: :new_account_user_registrantion
    post '/register/2/', to: 'my_devise/registrations#create', as: :create1_account_user_registrantion
    get '/register/2/', to: 'my_devise/registrations#show', as: :create_account_user_registrantion
    get '/register/3', to: 'my_devise/confirmations#show', as: :show_account_user_registrantation
    post 'register/3', to: 'my_devise/registrations#my_update', as: :update_account_user_registrantaion
    get '/forgot_password', to: 'devise/passwords#new', as: :new_user_password
    post '/forgot_password', to: 'my_devise/passwords#create', as: :password
    get '/reset_password/', to: 'my_devise/passwords#my_edit', as: :edit_password
    put '/forgot_password/', to: 'my_devise/passwords#update'
    get 'admin/login', to: 'my_devise/sessions#admin_login', as: :admin_login
    post 'admin/login', to: 'my_devise/sessions#do_admin_login', as: :new_admin_session
  end
  get '/jobs/', to: 'jobs#search', as: :search_job
  get '/jobs/favorite', to: 'jobs#favorite'
  post '/favorites/:id', to: 'favorites#create', as: :create_favorite
  get '/jobs/search/', to: 'jobs#search'
  post '/jobs/search/', to: 'jobs#search', as: :search_jobs
  get '/jobs/city/:city', to: 'jobs#search'
  get '/detail/:job_id', to: 'jobs#show'
  get '/jobs/industry/:industry', to: 'jobs#search'
  get '/my/', to: 'users#my', as: :user_my
  get '/apply/', to: 'applies#new'
  post '/confirm', to: 'applies#confirm1', as: :confirm1_apply
  get '/confirm', to: 'applies#confirm2', as: :confirm2_apply
  post '/done', to: 'applies#create', as: :create_apply
  get '/done', to: 'applies#done', as: :done_apply
  get 'my/info', to: 'users#info'
  post 'my/info', to: 'users#update', as: :update_user
  root to: 'jobs#index'
  get '/industrys', to: 'categories#show'
  get 'cities', to: 'cities#show'
  get '/my/favorites', to: 'favorites#index'
  delete '/my/favorites/:id', to: 'favorites#remove'
  get '/history', to: 'histories#index'
  delete '/history/:id', to: 'histories#remove', as: :remove_history
  get 'my/jobs', to: 'jobs#applied'
  get 'admin/applies', to: 'jobs#admin_job', as: :applies_admin
  get 'admin/download', to: 'jobs#admin_job', as: :export_applies
  post 'admin/applies', to: 'jobs#admin_job', as: :admin_job
  get '/suggestions/:keyword', to: 'jobs#spellcheck_solr'
end

Venjobs/app/models/Job.rb
class Job < ApplicationRecord
  belongs_to :category
  belongs_to :level
  belongs_to :province
  belongs_to :work_placement
  has_many :applies
  has_many :favorites
  validates :description, :name, presence: true
  searchable do
    long :id, as: :id_l, stored: true
    text :name, as: :name_acs, boost: 9
    text :benefit, as: :benefit_acs, boost: 4
    text :company_address, as: :company_address_acs, boost: 5
    text :company_name, as: :company_name_acs, boost: 6
    text :description, as: :description_acs, boost: 8
    text :requirement, as: :requirement_acs, boost: 3
    text :category_title, as: :category_title_acs, boost: 2 do |j|
      j.category.title
    end
    text :province_name, as: :province_name_acs, boost: 3 do |j|
      j.province.name
    end
    string :description_unikey, as: :description_unikey do |j|
      "#{j.name} #{j.description} #{j.benefit} #{j.requirement}"
    end
  end
end

Venjobs/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:spellcheck_solr, :search]
  before_action :admin_signin?, only: :admin_job
  def index
    @top_jobs = Job.order(created_at: :desc).limit(5)
    @top_jobs = Job.includes(:province).order(created_at: :desc).limit(5)
    @total_jobs = Job.all.count
    @total_cities = Province.all.count
    @top_industry = Category.order(count_job: :desc).select(:title, :count_job).limit(9)
    @total_industry = Category.all.count
    @top_cities = Province.order(count_job: :desc).select(:name, :count_job).limit(9)
  end

  def search
    all_city = Province.all.pluck(:name)
    keyword = params[:keyword].to_s.empty? ? ' ' : params[:keyword]
    keyword = case false
              when params[:keyword].to_s.empty?
                params[:keyword]
              when params[:city].to_s.empty?
                %Q("#{params[:city]}")
              when params[:industry].to_s.empty?
                %Q("#{params[:industry]}")
              else
                ''
              end
    @keyword = keyword
    @query = Job.search(include: %i[province work_placement favorites]) do
      fulltext keyword
        with(:province_name, params[:data]) if params[:data]
      facet(:city_facet) do
        all_city.each do |city_name|
          row(city_name) do
            with(:province_name, city_name)
          end
        end
      end
      paginate page: params[:page], per_page: 20
    end
    @job_list = @query.results
    @arr_job_id = Favorite.where('account_user_id = ? and job_id IN (?)', current_account_user,
                                 @job_list.pluck(:id)).pluck(:job_id)
    if params[:ajax_call] && params[:page].nil?
      render 'search_result', layout: false
    end
  end

  def show
    @job = Job.includes(:province, :category).find(params[:job_id])
    @favorite = Favorite.select(:id).where('account_user_id = ? and job_id = ?', current_account_user, @job.id)
    return if current_account_user.nil?
    return if History.new(account_user_id: current_account_user.email, job_id: params[:job_id]).save
    history = History.where('account_user_id = ? and job_id = ?', current_account_user.email, params[:job_id]).take
    history.touch(:updated_at)
  end

  def apply
    @apply = Apply.new(account_user: current_account_user, job_id: params[:job_id])
  end

  def applied
    @apply_list = Apply.select(:created_at, :job_id).where('account_user_id = ?',
                                                           current_account_user.email).order(created_at: :desc).includes(:job)
  end
  def admin_job
    @prp = {}
    @city_list = Province.order(:name).pluck(:name)
    @cate_list = Category.order(:title).pluck(:title)
    @result = Apply.all.includes(:job).order(created_at: :desc).page(params[:page]).per(20)
    return @result if params[:condition].nil?
    @prp = params.require(:condition).permit(:email,
                                             :city,
                                             :cate,
                                             :from_date,
                                             :to_date)
    @result = @result.where(email: @prp[:email]) unless @prp[:email].empty?
    arr_date = [ @prp['from_date(1i)'], @prp['from_date(2i)'], @prp['from_date(3i)'], @prp['to_date(1i)'], @prp['to_date(2i)'], @prp['to_date(3i)']]
      .map(&:to_i).each_slice(3).to_a
    unless (arr_date[0].inject(:*) * arr_date[1].inject(:*)).zero?
      year, month, day = arr_date[0].map(&:to_i)
      @prp[:from_date] = fdate = DateTime.new(year, month, day) rescue DateTime.new(year, month, 1).end_of_month
      year, month, day = arr_date[1].map(&:to_i)
      @prp[:to_date] = tdate = DateTime.new(year, month, day) rescue DateTime.new(year, month, 1).end_of_month
      @result = @result.where(created_at: fdate..tdate.end_of_day)
    end
    arr_job_id = @result.map(&:job_id)
    prp = @prp
    if !@prp[:city].empty? || !@prp[:cate].empty?
      query = Job.search(select: :id) do
        fulltext "\"#{prp[:city]}\"" unless prp[:city].empty?
        fulltext "\"#{prp[:cate]}\"" unless prp[:cate].empty?
        with(:id, arr_job_id)
      end
      @result = @result.where(job_id: query.results)
    end
    respond_to do |format|
      format.html
      format.csv do
        send_data Apply.export(@result), filename: 'job_applies.csv', type: 'text/csv'
      end
    end
  end
  def spellcheck_solr
    params[:keyword].nil? ? return : keyword = params[:keyword].split.last
    puts keyword
    query = Sunspot.search(Job) do
      keywords keyword
      spellcheck count: 7
    end
    result = query.spellcheck_suggestions[keyword]
    render json: { data: result }
  end
  def admin_signin?
    unless current_account_user && current_account_user.admin?
      flash[:alert] = 'You need to sign in or sign up before continuing!'
      return redirect_to :admin_login
    end
  end
end

Venjobs/app/views/jobs/admin_job.html.erb
<div class="admin-job-content">
  <h3 class="text-center">Applied Jobs</h3>
  <div class="condition-form">
    <%= simple_form_for :condition, url: admin_job_path, data: {turbo: false, method: :post }, id: :admin_search do |f| %>
      <%= f.input :email, input_html: {value: @prp[:email] } %>
      <%= f.input :city, wrapper: :my_select, collection: @city_list, prompt: 'Select city', selected: @prp[:city]%>
      <%= f.input :cate, wrapper: :my_select, collection: @cate_list, prompt: 'Select industry', selected: @prp[:cate]%> 
      <div class="row">
        <label class="form-label">Date</label>
        <div class="col">
          <div class="form-control group-select">
            <%= f.date_select :from_date, use_month_numbers: true, prompt: { day: 'Day', month: 'Month', year: 'Year'}, selected: @prp[:from_date] || Date.today - 1.months%> 
          </div>
        </div>
        <div class="col-1">
        </div>
        <div class="col">
          <div class="form-control group-select">
            <%= f.date_select :to_date, use_month_numbers: true, prompt: { day: 'Day', month: 'Month', year: 'Year'}, selected: @prp[:to_date] || Date.today%>
          </div>
        </div>
      </div>
      <div class="button row mt-4 d-flex justify-content-center">
        <button class="btn btn-primary col-2 me-5">Search</button>
        <%= link_to 'CSV Download', export_applies_path(params: request.params, format: :csv), class: 'btn btn-danger col-2 ms-5'%>
      </div>
    <% end %>
  </div>
  <div class="list-result">
    <% if @result %>
      <% @result.each do |item| %>
        <div class="job-item row">
          <div class="col-12">
            <h4><b><%= link_to item.job.name, "/detail/#{item.job.id}" %></b></h4>
            <p><b> Candidate Name: </b><%= link_to item.full_name, "/my?user_email=#{item.account_user_id}" %></p>
            <p><b> Candidate CV: </b><%= link_to item.cv.url, item.cv.url, download: item.cv_identifier %></p>
            <div class="row">
              <div class="col-8">
                <p><b> Candidate Email: </b><%= item.email%></p>
              </div>
              <div class="col-4">
                <p><b>Applied at: </b><%= item.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="d-flex justify-content-end mb-4">
    <%= paginate @result%>
  </div>
</div>

Venjobs/app/views/jobs/applied.html.erb
<div class="favorite-list-content">
  <h3 class="text-center mb-5">Applied Jobs</h3>
  <% @apply_list.each do |item| %>
    <div class="job-item row">
      <div class="col-12">
        <h4><b><%= link_to item.job.name, "/detail/#{item.job.id}" %></b></h4>
        <p><b>Description: </b><br/><%= item.job.description.truncate_words(255, omission: '...') unless item.job.description.to_s.empty? %></p>
        <div class="row">
          <div class="col-6">
            <% unless item.job.province.name.to_s.empty? %> 
              <p><b>Address: </b><%= "#{item.job.province.country}, #{item.job.province.name}"%><%= ", #{item.job.company_district}" unless item.job.company_district.to_s.empty?%></p>
            <% end %> 
          </div>
          <div class="col-3">
            <% unless item.job.salary.to_s.empty? %> 
              <p><b>Salary: </b><%= item.job.salary%></p>
            <% end %> 
          </div>
          <div class="col-3">
              <p><b>Applied at: </b><%= item.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

Venjobs/app/views/jobs/index.html.erb
<div class="job-list-content">
  <div class="key-visual">
    <%= image_tag 'key_visual.jpg' %> 
    <h4 class="text-center text-danger mt-3"><%= "#{@total_jobs} jobs" %> </h4>
  </div>
  <div class="form-search">
    <%= form_with url: "/jobs/search", method: :get do |f| %>
      <div class="form-group row">
        <%= f.text_field :keyword, class: 'form-control me-3 col', placeholder: 'Enter Search' %>
        <button type="submit" class="btn btn-danger ms-3 col-1">Search</button>
      </div>
    <% end %>
  </div>
  <div class="top-jobs">
    <h3 class="text-center mb-4">Lastes Jobs</h3>
    <% @top_jobs.each do |job| %>
      <div class="top-job-item">
        <%= link_to job.name, "/detail/#{job.id}" %></br></br>
        <% unless job.description.to_s.empty? %> 
          <p><b>Description: </b> <%= job.description.truncate(255, separator: ' ')%></p>
        <% end %> 
        <% unless job.salary.to_s.empty? %> 
          <p><b>Salary: </b> <%= job.salary%></p>
        <% end %> 
        <% unless job.province.name.to_s.empty? %> 
          <p><b>Province: </b> <%= job.province.name%></p>
        <% end %> 
      </div>
    <% end %>
  </div>
  <div class="top-cities">
    <h3 class="text-center">Top Citites</h3>
    <div class="top-cities-content row">
      <% @top_cities.each do |item| %>
        <div class="top-city-item col-4">
          <div class="col-12 card">
            <div class="card-body">
              <%= link_to item.name, "/jobs/city/#{item.name}"%>
            </div>
            <div class="card-footer">
              <%= link_to "Total #{item.count_job} jobs", "/jobs/city/#{item.name}"%>
            </div>
          </div>
        </div>
      <% end %>
    </div> 
    <p><%= link_to "More see #{@total_cities} cities", '/cities'%></p>
  </div>
  <div class="top-industry">
    <h3 class="text-center">Top Industry</h3>
    <div class="top-cities-content row">
      <% @top_industry.each do |item| %>
        <div class="top-industry-item col-4">
          <div class="col-12 card">
            <div class="card-body">
              <%= link_to item.title, "/jobs/industry/#{item.title}"%>
            </div>
            <div class="card-footer">
              <%= link_to "Total #{item.count_job} jobs", "/jobs/industry/#{item.title}"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <p><%= link_to "More see #{@total_industry} industrys", 'industrys'%></p>
  </div>
</div>

Venjobs/app/views/jobs/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
<div class="job-list-content">
  <div class="form-search">
    <%= form_with url: search_jobs_path, method: :get, data: { controller: 'hello' } do |f| %>
      <div class="form-group">
        <div class="row">
          <%= f.text_field :keyword, class: 'form-control me-3 col', placeholder: 'Enter Search', value: @keyword, id: "keyword" %>
          <button type="submit" class="btn btn-danger ms-3 col-1">Search</button>
        </div>
        <div class="data-list">
        <div class="arrow-up"></div>
          <div class="data-list-item" >
            <div class="data-list-item-p" id="data-list1">
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-3">
      <h4>Browse by city</h4>
      <ul class="list-group">
        <% for row in @query.facet(:city_facet).rows %> 
          <li class="list-group-item">
            <input type="checkbox" class="facet-check-box-city" name="city" value="<%= row.value %>" <%= params[:city_facet] == row.value ? 'checked' : '' %>>
            <%= row.value %> (<%= row.count %> ) 
          </li>
        <% end %> 
      </ul>
    </div>
    <div class="col-9">
      <div class="job-list">
        <div class="row text-center">
          <h4 class="col">Total: <%= @job_list.total_count %> </h4>
          <h4 class="col">Result for: <%= @keyword %> </h4>
        </div>
        <div class="d-flex justify-content-end mb-4">
          <%= paginate @job_list, window: 0, outer_window: 3%>
        </div>
        <% @job_list.each do |job| %>
          <div class="job-item row">
            <div class="col-10">
              <h4><b><%= link_to job.name, "/detail/#{job.id}" %></b></h4>
              <p><b>Description: </b><br/><%= job.description.truncate_words(255, omission: '...') unless job.description.to_s.empty? %></p>
              <div class="row">
                <div class="col-8">
                  <% unless job.province.name.to_s.empty? %> 
                    <p><b>Address: </b><%= "#{job.province.country}, #{job.province.name}"%><%= ", #{job.company_district}" unless job.company_district.to_s.empty?%></p>
                  <% end %> 
                </div>
                <div class="col-4">
                  <% unless job.salary.to_s.empty? %> 
                    <p><b>Salary: </b><%= job.salary%></p>
                  <% end %> 
                </div>
              </div>
            </div>
            <div class="job-item-favorite col-2">
              <% if @arr_job_id.include? job.id %> 
                <button onclick="add_to_favorite(<%= job.id %>)" id="<%= "btn_favorite_#{job.id}" %>" class="btn-favorite btn-solid"><i class="fa-solid fa-star"></i> Favorite</button>
              <% else %> 
                <button onclick="add_to_favorite(<%= job.id %>)" id="<%= "btn_favorite_#{job.id}" %>" class="btn-favorite"><i class="fa-solid fa-star"></i> Favorite</button>
              <% end %> 
            </div>
          </div>
        <% end %>
        <div class="d-flex justify-content-end mb-4">
          <%= paginate @job_list %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

Venjobs/app/views/jobs/search_result.html.erb
  <div class="job-list">
    <div class="row text-center">
      <h4 class="col">Total: <%= @job_list.total_count %> </h4>
      <h4 class="col">Result for: <%= @keyword %> </h4>
    </div>
    <div class="d-flex justify-content-end mb-4">
      <%= paginate @job_list, window: 0, outer_window: 3%>
    </div>
    <% @job_list.each do |job| %>
      <div class="job-item row">
        <div class="col-10">
          <h4><b><%= link_to job.name, "/detail/#{job.id}" %></b></h4>
          <p><b>Description: </b><br/><%= job.description.truncate_words(255, omission: '...') unless job.description.to_s.empty? %></p>
          <div class="row">
            <div class="col-8">
              <% unless job.province.name.to_s.empty? %> 
                <p><b>Address: </b><%= "#{job.province.country}, #{job.province.name}"%><%= ", #{job.company_district}" unless job.company_district.to_s.empty?%></p>
              <% end %> 
            </div>
            <div class="col-4">
              <% unless job.salary.to_s.empty? %> 
                <p><b>Salary: </b><%= job.salary%></p>
              <% end %> 
            </div>
          </div>
        </div>
        <div class="job-item-favorite col-2">
          <% if @arr_job_id.include? job.id %> 
            <button onclick="add_to_favorite(<%= job.id %>)" id="<%= "btn_favorite_#{job.id}" %>" class="btn-favorite btn-solid"><i class="fa-solid fa-star"></i> Favorite</button>
          <% else %> 
            <button onclick="add_to_favorite(<%= job.id %>)" id="<%= "btn_favorite_#{job.id}" %>" class="btn-favorite"><i class="fa-solid fa-star"></i> Favorite</button>
          <% end %> 
        </div>
      </div>
    <% end %>
    <div class="d-flex justify-content-end mb-4">
      <%= paginate @job_list %>
    </div>
  </div>

Venjobs/app/views/jobs/show.html.erb
<div class="job-detail-content">
  <h4><a href="/">TOP</a>
    <i class="fa-solid fa-angles-right"></i>
    <%= link_to @job.province.name, "/jobs/city/#{@job.province.name}" %>
    <i class="fa-solid fa-angles-right"></i>
    </i><span><%= @job.name%></span>
  </h4>
  <div class="job-detail-main-content">
    <div class="row">
      <div class="col-10">
        <h2><%= @job.name %></h2
        <p><b>Company: </b><%= @job.company_name %></p>
        <p><b>Location: </b><%= link_to @job.work_placement.name, "/jobs/city/#{@job.work_placement.name}" %> </p>
        <p><b>Salary: </b><%= @job.salary %></p>
        <p><b>Description: </b><%= @job.description%></p>
      </div>
      <div class="button col-2">
        <%=link_to "/apply?job_id=#{@job.id}", class: 'btn btn-primary' do %> 
          <i class="fa-solid fa-file-medical"></i> Apply
        <% end %> 
      </div>
    </div>
    <div class="button row mt-4">
      <div class="col-2">
        <%=link_to "/apply?job_id=#{@job.id}", class: 'btn btn-primary' do %> 
          <i class="fa-solid fa-file-medical"></i> Apply
        <% end %> 
      </div>
      <div class="col-2">
          <% if @favorite.empty? %> 
            <button onclick="add_to_favorite(<%= @job.id %>)" id="<%= "btn_favorite_#{@job.id}" %>" class="btn-favorite"><i class="fa-solid fa-star"></i> Favorite</button>
          <% else %> 
          <button onclick="add_to_favorite(<%= @job.id %>)" id="<%= "btn_favorite_#{@job.id}" %>" class="btn-favorite btn-solid"><i class="fa-solid fa-star"></i> Favorite</button>
          <% end %> 
      </div>
    </div>
  </div>
</div>