Venjobs/config/routes.rb
Rails.application.routes.draw do
  devise_for :account_users, skip: [:sessions]
  as :account_user do
    get '/login', to: 'devise/sessions#new', as: :new_account_user_session
    get '/register', to: 'devise/registrations#new'
    post '/login', to: 'my_devise/sessions#create', as: :account_user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_account_user_session
    get '/register/1', to: 'my_devise/registrations#new', as: :new_account_user_registrantion
    post '/register/2/', to: 'my_devise/registrations#create', as: :create1_account_user_registrantion
    get '/register/2/', to: 'my_devise/registrations#show', as: :create_account_user_registrantion
    get '/register/3', to: 'my_devise/confirmations#show', as: :show_account_user_registrantation
    post 'register/3', to: 'my_devise/registrations#my_update', as: :update_account_user_registrantaion
    get '/forgot_password', to: 'devise/passwords#new', as: :new_user_password
    post '/forgot_password', to: 'my_devise/passwords#create', as: :password
    get '/reset_password/', to: 'my_devise/passwords#my_edit', as: :edit_password
    put '/forgot_password/', to: 'my_devise/passwords#update'
    get 'admin/login', to: 'my_devise/sessions#admin_login', as: :admin_login
    post 'admin/login', to: 'my_devise/sessions#do_admin_login', as: :new_admin_session
  end
  get '/jobs/', to: 'jobs#search', as: :search_job
  get '/jobs/favorite', to: 'jobs#favorite'
  post '/favorites/:id', to: 'favorites#create', as: :create_favorite
  get '/jobs/search/', to: 'jobs#search'
  post '/jobs/search/', to: 'jobs#search', as: :search_jobs
  get '/jobs/city/:city', to: 'jobs#search'
  get '/detail/:job_id', to: 'jobs#show'
  get '/jobs/industry/:industry', to: 'jobs#search'
  get '/my/', to: 'users#my', as: :user_my
  get '/apply/', to: 'applies#new'
  post '/confirm', to: 'applies#confirm1', as: :confirm1_apply
  get '/confirm', to: 'applies#confirm2', as: :confirm2_apply
  post '/done', to: 'applies#create', as: :create_apply
  get '/done', to: 'applies#done', as: :done_apply
  get 'my/info', to: 'users#info'
  post 'my/info', to: 'users#update', as: :update_user
  root to: 'jobs#index'
  get '/industrys', to: 'categories#show'
  get 'cities', to: 'cities#show'
  get '/my/favorites', to: 'favorites#index'
  delete '/my/favorites/:id', to: 'favorites#remove'
  get '/history', to: 'histories#index'
  delete '/history/:id', to: 'histories#remove', as: :remove_history
  get 'my/jobs', to: 'jobs#applied'
  get 'admin/applies', to: 'jobs#admin_job', as: :applies_admin
  get 'admin/download', to: 'jobs#admin_job', as: :export_applies
  post 'admin/applies', to: 'jobs#admin_job', as: :admin_job
  get '/suggestions/:keyword', to: 'jobs#spellcheck_solr'
end

Venjobs/app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'bcrypt'
  before_action :authenticate_account_user!, only: [:my]
  before_action :check_old_password!, only: [:update]
  def my
    if params[:user_email]
      @user = AccountUser.find(params[:user_email])
      return
    end
    @user = current_account_user
  end

  def info
    @user = current_account_user
  end

  def update
    user = AccountUser.find(@user.email)
    result = if @user.cv?
               user.update(full_name: @user.full_name,
                           cv: @user.cv,
                           encrypted_password: @user.encrypted_password)
             else
               user.update(full_name: @user.full_name,
                           encrypted_password: @user.encrypted_password)
             end
    if result
      flash[:notice] = 'Update infomation successfully!'
      return redirect_to user_my_path
    else
      flash.now[:alert] = 'update fails!'
    end
    render 'info'
  end

  def check_old_password!
    require_params = params.require(:account_user)
    @user = AccountUser.new(require_params.permit(:email,
                                                  :full_name,
                                                  :cv))
    @user.encrypted_password = require_params[:old_password]
    unless @user.valid?
      @user.errors.add(:old_password, '')
      return render 'info'
    end
    unless BCrypt::Password.new(current_account_user.encrypted_password) == @user.encrypted_password
      @user.errors.add(:old_password, '')
      @user.errors.add(:encrypted_password, 'Old password is invalid!')
      return render 'info'
    end
    if require_params[:new_password].blank?
      @user.encrypted_password = current_account_user.encrypted_password
    elsif require_params[:new_password].length >= 8 && require_params[:new_password].length <= 12
      @user.encrypted_password = BCrypt::Password.create(require_params[:new_password])
    else
      @user.errors.add(:new_password, 'Password\'s between 8 to 12 characters')
      render 'info'
    end
  end
end

Venjobs/app/views/users/history.html.erb
<div class="favorite-list-content">
  <h3 class="text-center mb-5">History</h3>
  <% unless @job_list.empty? %> 
    <% @job_list.each do |job| %>
      <label class="d-block">
        <div class="job-item row">
          <div class="col-10">
            <div class="row">
              <div class="form-check col-1">
                <input onclick="apply_job(<%= job.id %>)" class="form-check-input" type="radio" name="apply_radio"/>
              </div>
              <div class="col-11">
                <h4><b><%= link_to job.name, "/detail/#{job.id}" %></b></h4>
                <p><b>Description: </b><br/><%= job.description.truncate_words(255, omission: '...') unless job.description.to_s.empty? %></p>
                <div class="row">
                  <div class="col-8">
                    <% unless job.province.name.to_s.empty? %> 
                      <p><b>Address: </b><%= "#{job.province.country}, #{job.province.name}"%><%= ", #{job.company_district}" unless job.company_district.to_s.empty?%></p>
                    <% end %> 
                  </div>
                  <div class="col-4">
                    <% unless job.salary.to_s.empty? %> 
                      <p><b>Salary: </b><%= job.salary%></p>
                    <% end %> 
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="job-item-favorite col-2">
            <%= link_to "/history/#{job.id}", data: {turbo_method: :delete}, class: 'btn btn-danger' do %>
              <i class="fa-solid fa-star"></i> Remove
            <% end %> 
          </div>
        </div>
      </label>
    <% end %>
    <div class="button">
      <div class="col-2">
        <%=link_to "/apply?job_id=#{@job_list[0].id}", class: 'btn btn-primary', id: 'apply_link' do %> 
          <i class="fa-solid fa-file-medical"></i> Apply
        <% end %> 
      <% else %> 
        <h4 class="text-center">Empty!</h4>
      <% end %> 
      </div>
    </div>
</div>

Venjobs/app/views/users/info.html.erb
<div class="info-content">
  <h3 class="text-center">My Page</h3>
  <% if alert %> 
    <p class="alert-error"><%= alert if alert %></p>
  <% end %> 
  <% if alert %> 
    <p class="text-success"><%= notice if notice %></p> 
  <% end %> 
  <%= simple_form_for @user, url: update_user_path, data: { turbo: false }, method: :post do |f| %>
    <%= f.input :email, readonly: true %>
    <%= f.input :full_name, error: f.error(:full_name)%>
    <%= f.input :cv, label: 'My CV', error: f.error(:cv)%>
    <%= f.input :new_password, error: f.error(:new_password) %>
    <%= f.input :old_password, error: f.error(:encrypted_password)%>
    <div class="button">
      <button class="btn btn-primary">Update</button>
    </div>
  <% end %> 
</div>

Venjobs/app/views/users/my.html.erb
<div class="my-content">
  <h3 class="text-center">My Page</h3>
  <p class="text-center text-success"><%= notice if notice %></p>
  <div>
    <label class="form-label">Full name</label>
    <label class="form-control mb-3"><%= @user.full_name %> </label>
    <label class="form-label">Email</label>
    <label class="form-control mb-3"><%= @user.email%> </label>
    <label class="form-label">CV</label>
    <% if @user.cv? %> 
      <%= link_to @user.cv.url, download: @user.cv.file.filename, class: 'form-control mb-3' do %> 
        <i class="fa-solid fa-download"></i> <%= @user.cv.url %> 
      <% end %> 
    <% else %> 
      <label class="form-control mb-3">Please! Upload your CV</label>
    <% end %> 
    <div class="button row mt-4 d-flex justify-content-center">
      <%= link_to 'Update', "/my/info", class: 'btn btn-danger col-1 me-5'%>
      <%= link_to 'My Jobs', "/my/jobs", class: 'btn btn-primary col-1 me-5'%>
    </div>
  </div>
</div>