Venjobs/config/routes.rb
Rails.application.routes.draw do
  devise_for :account_users, skip: [:sessions]
  as :account_user do
    get '/login', to: 'devise/sessions#new', as: :new_account_user_session
    get '/register', to: 'devise/registrations#new'
    post '/login', to: 'my_devise/sessions#create', as: :account_user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_account_user_session
    get '/register/1', to: 'my_devise/registrations#new', as: :new_account_user_registrantion
    post '/register/2/', to: 'my_devise/registrations#create', as: :create1_account_user_registrantion
    get '/register/2/', to: 'my_devise/registrations#show', as: :create_account_user_registrantion
    get '/register/3', to: 'my_devise/confirmations#show', as: :show_account_user_registrantation
    post 'register/3', to: 'my_devise/registrations#my_update', as: :update_account_user_registrantaion
    get '/forgot_password', to: 'devise/passwords#new', as: :new_user_password
    post '/forgot_password', to: 'my_devise/passwords#create', as: :password
    get '/reset_password/', to: 'my_devise/passwords#my_edit', as: :edit_password
    put '/forgot_password/', to: 'my_devise/passwords#update'
    get 'admin/login', to: 'my_devise/sessions#admin_login', as: :admin_login
    post 'admin/login', to: 'my_devise/sessions#do_admin_login', as: :new_admin_session
  end
  get '/jobs/', to: 'jobs#search', as: :search_job
  get '/jobs/favorite', to: 'jobs#favorite'
  post '/favorites/:id', to: 'favorites#create', as: :create_favorite
  get '/jobs/search/', to: 'jobs#search'
  post '/jobs/search/', to: 'jobs#search', as: :search_jobs
  get '/jobs/city/:city', to: 'jobs#search'
  get '/detail/:job_id', to: 'jobs#show'
  get '/jobs/industry/:industry', to: 'jobs#search'
  get '/my/', to: 'users#my', as: :user_my
  get '/apply/', to: 'applies#new'
  post '/confirm', to: 'applies#confirm1', as: :confirm1_apply
  get '/confirm', to: 'applies#confirm2', as: :confirm2_apply
  post '/done', to: 'applies#create', as: :create_apply
  get '/done', to: 'applies#done', as: :done_apply
  get 'my/info', to: 'users#info'
  post 'my/info', to: 'users#update', as: :update_user
  root to: 'jobs#index'
  get '/industrys', to: 'categories#show'
  get 'cities', to: 'cities#show'
  get '/my/favorites', to: 'favorites#index'
  delete '/my/favorites/:id', to: 'favorites#remove'
  get '/history', to: 'histories#index'
  delete '/history/:id', to: 'histories#remove', as: :remove_history
  get 'my/jobs', to: 'jobs#applied'
  get 'admin/applies', to: 'jobs#admin_job', as: :applies_admin
  get 'admin/download', to: 'jobs#admin_job', as: :export_applies
  post 'admin/applies', to: 'jobs#admin_job', as: :admin_job
  get '/suggestions/:keyword', to: 'jobs#spellcheck_solr'
end

Venjobs/app/models/Apply.rb
class Apply < ApplicationRecord
  require 'csv'
  belongs_to :account_user
  belongs_to :job
  mount_uploader :cv, CvUploader
  validates :full_name, length: {
    maximum: 200,
    message: 'Full name max 200 character!'
  }, presence: { message: 'Full name is required!' }
  validates :email, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'Format email is valid!'
  }
  validates :account_user_id, uniqueness: { scope: :job_id, message: 'You have submitted your CV for this job!' }
  def self.export(jobs)
    CSV.generate(col_sep: ',') do |csv|
      csv << attribute_names
      jobs.find_each do |item|
        csv << item.attributes.values
      end
    end
  end
end

Venjobs/app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :authenticate_account_user!, only: %i[new create confirm1]
  def new
    unless current_account_user.cv?
      flash[:alert] = 'You need to uploaded your CV before continuing.'
      redirect_to update_user_path
    end
    session[:job_id] = params[:job_id]
    @apply = if session[:apply].nil?
               Apply.new(account_user: current_account_user, job_id: params[:job_id])
             else
               Apply.new(session[:apply])
             end
  end

  def confirm1
    permit_params = params.require(:apply).permit(:full_name, :email, :cv)
    apply = Apply.new(full_name: permit_params[:full_name], email: permit_params[:email],
                      account_user: current_account_user,
                      job_id: session[:job_id])
    unless apply.valid?
      flash[:alert] = 'You have submitted your CV for this job!' unless apply.errors[:account_user_id].blank?
      @apply = apply
      return render 'new'
    end
    session[:apply] = apply
    redirect_to action: 'confirm2'
  end

  def confirm2
    apply_hash = session[:apply]
    @apply = Apply.new(apply_hash)
  end

  def create
    hash_apply = params.require(:apply).permit(:full_name, :email)
    @apply = Apply.new(hash_apply)
    @apply.cv = current_account_user.cv
    @apply.account_user_id = current_account_user.email
    @apply.job_id = session[:job_id]
    if @apply.save
      @job = Job.find(@apply.job_id)
      ApplyJobMailers.with(user: current_account_user, apply_job: @apply, job: @job).confirm_apply_job.deliver_later
      ApplyJobMailers.with(apply_job: @apply, job: @job).admin_job_applied.deliver_later
    else
      flash[:alert] = 'You have submitted your CV for this job!'
      return redirect_to action: 'confirm2'
    end
    session.delete(:job_id)
    session.delete(:apply)
    redirect_to done_apply_url
  end
end

Venjobs/app/views/applies/confirm2.html.erb
<div class="job-apply">
  <div class="ribbon">
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">1</p><p>New</p></div></div>
    <div class="pentagon-enable"><div class="ribbon-content"><p class="fa-solid-circle">2</p><p>Confirm</p></div></div>
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">3</p><p>Finish</p></div></div>
  </div>
  <div class="apply-form">
    <h3 class="text-center">Apply Form</h3>
    <p class="alert-error"> <%= alert if alert%></p>
    <%= simple_form_for @apply, url: create_apply_path, html: {multipart: true, method: :post}, data: {turbo: false} do |f| %> 
      <%= f.input :full_name, readonly: true%>
      <%= f.input :email, readonly: true%> 
      <label class="form-label">CV</label>
      <label class="form-control"><%= current_account_user.cv.file.filename %> </label>
      <div class="button row mt-4 d-flex justify-content-center">
        <%= link_to 'Edit', "/apply?job_id=#{session[:job_id]}", class: 'btn btn-success col-1 me-5'%>
        <button class="btn btn-primary col-1 ms-5">Done</button>
      </div>
    <% end %>
  </div>
</div>

Venjobs/app/views/applies/done.html.erb
<div class="job-apply">
  <div class="ribbon">
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">1</p><p>New</p></div></div>
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">2</p><p>Confirm</p></div></div>
    <div class="pentagon-enable"><div class="ribbon-content"><p class="fa-solid-circle">3</p><p>Finish</p></div></div>
  </div>
  <div class="done-content">
    <p>Thank you for apply</p>
    <%= link_to 'Back to TOP page', '/', class: 'mt-4'%> 
  </div>
</div>

Venjobs/app/views/applies/new.html.erb
<div class="job-apply">
  <div class="ribbon">
    <div class="pentagon-enable"><div class="ribbon-content"><p class="fa-solid-circle">1</p><p>New</p></div></div>
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">2</p><p>Confirm</p></div></div>
    <div class="pentagon-disable"><div class="ribbon-content"><p class="fa-solid-circle">3</p><p>Finish</p></div></div>
  </div>
  <div class="apply-form">
    <h3 class="text-center">Apply Form</h3>
    <p class="alert-error"> <%= alert if alert%></p>
    <%= simple_form_for @apply, url: confirm1_apply_path, html: {multipart: true, method: :post}, data: {turbo: false} do |f| %> 
      <%= f.input :full_name, error: f.error(:full_name), input_html:{value: current_account_user.full_name} %>
      <%= f.input :email, input_html:{value: current_account_user.email}%> 
    <label class="form-label">CV</label>
    <%= link_to current_account_user.cv.url, download: current_account_user.cv.file.filename, class: 'form-control mt-2' do %> 
      <i class="fa-solid fa-download"></i> <%= current_account_user.cv.url %> 
  <% end %> 
  <div class="button-new">
    <button class="btn btn-primary mt-4">Confirm</button>
  </div>
<% end %>
  </div>
</div>